### ISSUE TITLE
Invoice creation on authorized orders

### ISSUE THREAD

**Issue by FreekVandeursen** [mollie/magento2#106]
Currently the processTransaction function will create an invoice with status pending in Magento when an order has the status Authorized in Mollie, for example Klarna Pay Later orders.

Legally I don't think an invoice is required at this point yet, since the customer has no obligation to pay yet. Therefore in my opinion it would make more sense to delay the creation of the invoice to the point when the shipment has been created.

Would it be possible to give the merchants an option whether to create an invoice in Magento or not when the order has status Authorized?

**Comment by Frank-Magmodules** [comment]
Hi @FreekVandeursen, Yes, that's correct. A pending invoice is created upon an Authorized order. I'm not sure about the legal point of view on this, but we will add this as an option on the next release.

**Comment by FreekVandeursen** [comment]
Hi @Frank-Magmodules ,

A good example why this change would be useful is the following scenario:

Create an order with 2 order items and pay with Klarna.
Create a shipment in Magento for 1 of the order items.

Now I would expect to see an invoice in Magento for the order item that is shipped, with status Paid.

The actual result is that Magento has an invoice for both order items, with status paid. So in Magento the full order amount is listed as captured/paid, which does not correspond with the actual status in Mollie.

**Comment by Frank-Magmodules** [comment]
Hi @FreekVandeursen . 

We have just released a new version [v1.6.4](https://github.com/mollie/magento2/releases/tag/v1.6.4) that adds an option: "When to create the invoice?". 

There are two options:
* On Authorize: Create a full invoice when the order is authorized.
* On Shipment: Create a (partial) invoice when a shipment is created.

This also adds support for partial shipments and partial invoices.
Thanks again for the input! 

Closing this issue now, but please feel free to reopen the issue if needed.

**Comment by digikeijs** [comment]
@Frank-Magmodules I am currently testing this option "When to create the invoice?". but when I change it to shipment but I, for example, have an ideal payment it still creates the invoice.

how is that possible?

**Comment by web4exposure-org** [comment]
@Frank-Magmodules 
Hi, we have a problem regarding this as well and we are wondering about the specifics of this setting's effect.

Our use case is as follows. Users place an order, after which the invoice is created (we have 'On Authorize' enabled). This means, Klarna will receive the invoice and we will have ~30 days to ship the order, or it expires? However, when we have a shipping delay (or long lead time, for example of 30 days), the Klarna order will expire before we ship the order. After which, we ship the order and the customer does not have to pay through Klarna, since it has expired.

If changing this to "On Shipment", will the customer be validated (financial audit, fraud check) on authorization and will this help with our situation? That means, giving us time to ship the order, even if that takes 1 month and after that, creating the invoice and creating the pending payment in Klarna for proper handling.
