### ISSUE TITLE
Email template is not defined

### ISSUE THREAD

**Issue by franckcharpentier** [mollie/magento2#251]
In Magento 2.3.4, after module installation, we can no longer access payment methods.

And the following error is logged:
main.CRITICAL: Email template 'payment_fr_mollie_mollie_general_second_chance_email_template' is not defined. [] []

**Comment by Frank-Magmodules** [comment]
@franckcharpentier, Thank you for opening this issue.
We have reproduced this issue and create a fix to make sure the right template path is generated.
This solution is currently being tested so that it can be included in the release early next week, we will update this issue once the release is there.

Frank

**Comment by Frank-Magmodules** [comment]
Hi @franckcharpentier, thanks again for the detailed issue report. The issue has been resolved in the [v1.13.0](https://github.com/mollie/magento2/releases/tag/v1.13.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
