### ISSUE TITLE
Transaction Start Endpoint : An ID is needed. Set the ID and try again.

### ISSUE THREAD

**Issue by shafikhaan** [mollie/magento2#304]
**Describe the bug**
I am calling **_/rest/all/V1/mollie/transaction/start_** and passing admin token in the headers and "token" : xxxxxxxx in the body provided by **_mollie/payment-token_** but i am getting response :

```
{
    "message": "An ID is needed. Set the ID and try again."
}
```

**Used versions**
- *Magento Version number(eg 2.3.0)*:
- *Open source/Enterprise/B2b*:
- *Mollie version number (1.17.0)*:

**Expected behavior**
I am expecting a redirect URL in the response as per the documentation

**Actual behavior**
```
{
    "message": "An ID is needed. Set the ID and try again."
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8849114/93859125-a5052480-fcd6-11ea-8df9-1f26ce4db095.png)

**Comment by Frank-Magmodules** [comment]
Hello @shafikhaan,
We just did a test but it looks like everything is working. Did you follow the steps as described in the WIKI?
https://github.com/mollie/magento2/wiki/PWA-integration

**Comment by Frank-Magmodules** [comment]
Hi @shafikhaan ,

Any updates on this? 
Thanks!

**Comment by Frank-Magmodules** [comment]
@shafikhaan , Due to inactivity we are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by royduin** [comment]
You need to place the order before you can start a transaction.

**Comment by Timebutt** [comment]
For anybody else facing this at some point in the future: I just ran into this exact problem, and it's caused by not meticulously using the same order as described in the [documentation](https://github.com/mollie/magento2/wiki/REST-Integration). 

```
Create cart
Add products
Set shipping information
Create payment token
Place order
Start transaction
```

It's vital that you create the payment token (`GET /V1/carts/mine/mollie/payment-token` or `GET /V1/guest-carts/:cartId/mollie/payment-token`) before (!) you place the order, not after! If you request the payment token after placing the order, it'll throw the `An ID is needed. Set the ID and try again.` error.
