### ISSUE TITLE
Location of the payment method changes based on the Country setting

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#307]
**Describe the bug**
I enabled all payment methods for all available countries.
I decided to change it, so that BanContact is only visible for Belgium-customers.

I'd expect that the BanContact-payment method would stay at the same position in the list, so the "sorteervolgorde" would be honoured.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.3
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: v1.17.0

**To Reproduce**
1. Make the payment method BanContact only available in Belgium:
![image](https://user-images.githubusercontent.com/17478858/94414260-6a8b0400-017c-11eb-99e6-9a3fdab863a2.png)
2. Go the the checkout and check the position of the BanContact payment method. 

**Expected behavior**
BanContact should stay at the same position as before (2nd place):
![image](https://user-images.githubusercontent.com/17478858/94413955-0ec07b00-017c-11eb-8bd5-5f199a668e79.png)

**Actual behavior**
BanContact stood at the end of the list:
![image](https://user-images.githubusercontent.com/17478858/94413911-ffd9c880-017b-11eb-8fd1-7919aa4bc39e.png)

**Comment by Frank-Magmodules** [comment]
Hello @gerben86,

Thank you for opening this issue. This happens due to the way Magento renders the payment methods. The code responsible for this is found here: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/js/view/payment/list.js#L132-L159

This only happens when you go through the checkout this way:
- Fill in shipping address with country A.
- Go to payment methods.
- Go back to the shipping address, change to country B.

The second time Magento will render only the payment methods that are not rendered before and hereby adding them to the list with existing payment methods. If you fill in the correct country right away then the list with payment methods will get rendered the way as expected.

**Comment by gerben86** [comment]
@Frank-Magmodules ,

You're right, this is indeed the behaviour.
In the first attempt the BanContact-payment method is in the correct position.

Thanks! I'll close this bug.
