### ISSUE TITLE
Unable to show payment gateway on front issue

### ISSUE THREAD

**Issue by Krupaly2k** [mollie/magento2#35]
Hi Support,

I am using dev environment with live credentials for mollie payment method. After all configuration, it is not showing any payment method on frontend. Please help me to resolve this issue soon

**Comment by magmodules** [comment]
Hi, what are the results of the "Self Test" (button in config) and "Test Apikey" (button in config)?
If these all pass, please enable the debug option, open the checkout and check the log file under: var/log/mollie.log.

**Comment by skitter-anton** [comment]
Hi, I just installed the plugin through CLI/composer without any problems. I set the API keys in the backend and tried both modes (test/live). Selftest and Test api key both give success. Also I set the status to active and activated 2 payment methods. The problem is that the payment method does not show on the frontend. If I disable other payment methods I get "No Payment method available." I tried to refresh cache but no success.

**Comment by magmodules** [comment]
Hi, can you check: https://github.com/mollie/magento2/wiki/Troubleshooting 
- is the default currency of the storeview  EURO?
- Are methods active in Mollie Dashboard?
- Does the order value meet the Min & Max values of the Payment Method?

**Comment by skitter-anton** [comment]
Hi,
The default currency = EURO
The methods are active
Order value min & max are empty (i assume that is OK)

**Comment by magmodules** [comment]
What version of M2 are you running?

Some things to check:
- Can you enable the debug option, open the checkout and check the log file under: var/log/mollie.log? - And did you recompile after installation?

**Comment by skitter-anton** [comment]
I am using 2.1.6. I ran "php bin/magento setup:upgrade" again and now it seems ok. Weird since I did it before. Anyway, it works. Thanks for the fast support!

**Comment by magmodules** [comment]
That's perfect. Thanks for the notice!
