### ISSUE TITLE
Refund via API not working

### ISSUE THREAD

**Issue by azngeek** [mollie/magento2#383]
**Describe the bug**

I try to execute a refund using the API. The api works fine as i can see that a credit memo for the online refund is created. The issue is that the refunded items will not be refunded.

![image](https://user-images.githubusercontent.com/213429/116539241-db4bf780-a8e8-11eb-9847-e312effc284d.png)

Instead the Mollie-Dashboards shows that there is no refund registered.

`
{{endpoint}}/rest/all/V1/invoice/<invoice_entity_id>/refund
`

Payload:

`
{
  "items": [
    {
      "order_item_id": <quote_item_id>,
      "qty": 1
    }
  ],
  "notify": true
}
`

**Used versions**
- *Magento Version 2.4.1
- Enterprise
- *Mollie version number v1.25.1

**To Reproduce**

1. Create an order using graphql, etc.
2. Refund the order using the endpoint `{{endpoint}}/rest/all/V1/invoice/<invoice_entity_id>/refund`
3. A credit memo should be created in the Magento backend
4. No refund was registered in the Mollie backend.

**Expected behavior**

When executing a refund using the Magento-API, then a refund must be issued in the mollie dashboard.

**Actual behavior**

When executing a refund using the Magento-API, then no refund is registered.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @azngeek, thank you for opening this issue.

Looking at the payload you are doing an offline refund at this moment.
To make an online refund you need to add  "isOnline": true to your payload.

Example:
`{ "items": [ { "order_item_id": 2189, "qty": 1 } ], "notify": true, "isOnline": true }`

This will also trigger a refund on the Mollie platform. 
Closing this issue now, as this is not an issue with the module, but feel free to reopen if you think otherwise

**Comment by azngeek** [comment]
Thanks! That was it.
