### ISSUE TITLE
No payment option available while creating an order in adminhtml

### ISSUE THREAD

**Issue by MarianNapi** [mollie/magento2#395]
**Used versions**
- *Magento Version number*: 2.4.2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.26

**To Reproduce**
1. Go to "orders" in adminhtml
2. Create a new order and add a product
3. Scroll down to 'payment methods'
4. There is no payment option available

**Expected behavior**
Every activated payment option should be visible and able to select.

**Actual behavior**
There is no payment option available.

**Comment by Frank-Magmodules** [comment]
HI @MarianNapi ,

To activate back-end payment methods, you should enable and configurable the `Payment Link / Admin Payment` payment method in the Mollie configuration section within your Magento back-end. 

So thank you for opening this issue but I'm sure that your issue is going to be solved by enabling this option so we are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by MarianNapi** [comment]
Hey @Frank-Magmodules 

You were right, I just had to enable it in my back-end. Sadly this isn't mentioned anywhere in the small documentation that's available for this plugin. Maybe I'm just too stupid but I think the point is important enough to write it into the documentation.

**Comment by Frank-Magmodules** [comment]
Hi @MarianNapi ,

Good idea! Just added a guide for this right [here](https://github.com/mollie/magento2/wiki/Using-the-Payment-Link-to-create-an-Admin-payment) in the Mollie Wiki. Have a good day!
