### ISSUE TITLE
View order details as guest

### ISSUE THREAD

**Issue by joggienl** [mollie/magento2#418]
Hi,

This issue is more of a question then it is either a bug or feature request.

On our webshop (a PWA using graphql and the mollie module) after payment I can lookup the order details via the `mollieCustomerOrder` query. 

Is there a way to get details like `invoice` and `credit_memo` as a guest user?

For example if I try this as not authenticated user (as a guest) I get this:

```graphql
query {
  mollieCustomerOrder(hash: "MDozOllXRm5PWUU3dkk3REY2b1pQZzh4ZGVENTl1d3d6SExEL0N2eDVVc3ZNQT09") {
    id
    invoices {
      items {
        product_name
      }
    }
  }  
}

# output:
{
  "errors": [
    {
      "debugMessage": "\"model\" value should be specified",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 35,
          "column": 5
        }
      ],
      "path": [
        "mollieCustomerOrder",
        "invoices"
      ]
    }
  ],
  "data": {
    "mollieCustomerOrder": null
  }
}
```

It would be nice to get the order details of any user, not just authenticated users. I could imagine some security measurements like asking for some details just like you get when you acces this page on any magento instance: http://some-magento-host/guest/sales/order.

Is this something that could be done with magento / mollie and graphql?

**Comment by Frank-Magmodules** [comment]
Hello @joggienl,

Unfortunately, this is not available within Magento’s GraphQL, and so it’s also not available in the Mollie GraphQL endpoints. You can, however, retrieve invoices and credit memos using Magento’s REST API. You most likely need to have some authentication of your PWA user in place as it would be otherwise possible for everyone to retrieve all invoices & credit memos.

**Comment by joggienl** [comment]
Hello @Frank-Magmodules, thanks for the reply, much appreciated!

The real challenge I guess is that to be able to get orders from guest buyers you need admin powers. The graphql endpoints do not really support that.

The webshop is using serverside rendering (nextjs) so I am thinking about a similar approach via an api route that at least hides the admin part for the user.

Like I said, the luma theme has something both rest and graphql does not support out of the box. A form where you can fill in some details that allows the system to allow access to order details. See the image below, the url I mentioned earlier was not correct though, it should have been http://some-magento-host/sales/guest/form. Then you get a page with content like the image below.

Just out of curiosity, would it be possible for the mollie code that runs at the magento instance to get and return guest order details? I am not sure if it can. Based on input like as the image below it could be determined to return information (or not).

![image](https://user-images.githubusercontent.com/1089150/127469163-e5755359-aeaa-4f27-9b7c-04a0a9e91b56.png)

**Comment by Frank-Magmodules** [comment]
Hello @joggienl,

Yes, it is possible to get guest order details using the Mollie extension, but you can only retrieve them by the order hash. This means 2 things:

\- This will only work for orders placed using Mollie payment methods.  
\- You can't fetch them by using the input as shown in your screenshot.   
  
If you want to retrieve customer/guest orders this way you need to extend GrahpQL and implement your own query to fetch this data. You can look in the Mollie extension how we extended GraphQL for some examples.   
You need 2 parts:

1\. Extend GraphQL itself:   
[https://github.com/mollie/magento2/blob/master/etc/schema.graphqls#L49-L54](https://github.com/mollie/magento2/blob/master/etc/schema.graphqls#L49-L54)  
  
2\. Implement a resolver to fetch the data: [https://github.com/mollie/magento2/blob/master/GraphQL/Resolver/Checkout/MollieCustomerOrder.php](https://github.com/mollie/magento2/blob/master/GraphQL/Resolver/Checkout/MollieCustomerOrder.php)

Since this is something outside of the plugin's function and not going to implement it, I'm closing this issue now.   
Despite that, I hope that we have helped you on your way with the above explanation.

**Comment by joggienl** [comment]
Hello @Frank-Magmodules,

Thanks for the reply and hints on how to extend it, very helpful.
