### ISSUE TITLE
SEPA payment uncancel and invoice order

### ISSUE THREAD

**Issue by sm131313** [mollie/magento2#432]
Most stores are using an automatic order canceller to free up stock when an order has not been paid for within XX hours. 
The issue would be here that if a customer decides to pay with SEPA bank transfer the payment is valid for 8 days or so. 

If payment has not arrived within these days we have an extension that cancels the order and free's up the stock so it can be re-ordered by another customer. If Mollie receives the payment after this amount of days with current Magento status as cancelled Mollie does not uncancel and invoice the order. It leaves the order as cancelled. 

This causes us to receive some email after an amount of days from the customer stating they have paid for the order but not received it. 

What should be done here is that if a payment is received after it has been cancelled then Mollie should uncancel the order, invoice it, set it to processing so it can be shipped and not ignored with the order left in cancelation state.

**Comment by Frank-Magmodules** [comment]
Hi @sm131313 ,

Thank you for opening this issue. 

We recommend using another 'pending' status as the default Magento pending status can automatically cancel the order before the payment expiry time is reached. You can set this custom state within the configuration of the Banktransfer within the Mollie Payment Plugin.

By default the status "Pending Payment" is not visible for customers, therefore we advise you to create a new status for this, which should also be visible to the customer, informing them they still have to complete their payment.

Please let me know if this helps you out so we can close the issue once clear.

**Comment by Frank-Magmodules** [comment]
Hi @sm131313 ,

My answer on 4oct was mainly about the cancellation status regarding the [Pending Payment Order Lifetime](https://docs.magento.com/user-guide/sales/order-pending-payment-lifetime.html) but I'm not sure if this was the right answer to your question. 

I'm not sure if this is a configuration misunderstanding/issue within Magento and/or the Mollie plugin so can you please share the original bug report like below so we can investigate this with you?

---

**Describe the bug**  
A clear and concise description of what the bug is.

**Used versions**  
\- \*Magento Version number(eg 2.3.5)\*:  
\- \*Open source/Enterprise/B2b\*:  
\- \*Mollie version number (Check configuration)\*:

**To Reproduce**  
Steps to reproduce the behavior:  
1\. Go to '...'  
2\. Click on '....'  
3\. Scroll down to '....'  
4\. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Actual behavior**  
A clear and concise description of what actually happens.

**Screenshots**  
If applicable, add screenshots to help explain your problem.

**Additional context**  
Add any other context about the problem here.

**Comment by Frank-Magmodules** [comment]
HI @sm131313 ,

We didn't receive any response on this issue anymore, therefore, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our \[contact form\](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Comment by sm131313** [comment]
Hi, I must reopen this. We did test with different payment status. The issue we have now is that Magento does not cancel unpaid orders when the Pending lifetime expiry reaches. 
Currently we have it set to 9 days. However after 9 days the orders are still Pending and not cancelled while in Mollie website backend the orders have status EXPIRED. 

Why doesn't Mollie sync EXPIRED statuses with Magento and also Cancels Magento pending orders the same time?
