### ISSUE TITLE
Payment method not showing up in onestep checkout

### ISSUE THREAD

**Issue by Yasp0** [mollie/magento2#46]
I am using a onestep checkout extension from BSS commerce. The default payment methodes do show up, but the Mollie payment methods don't.

I followed all the checkpoints on https://github.com/mollie/magento2/wiki/Troubleshooting, but no succes. Can you resolve this issue or do I need to contact BSS commerce?

![image](https://user-images.githubusercontent.com/5689226/35670450-edb33848-0738-11e8-93a9-6e78edd043fc.png)

Magento version: 2.2.2

**Comment by Frank-Magmodules** [comment]
Hi @Yasp0 ,

Thanks for your message. I've got some questions to get a better sight on your problem.
Are you running the latest version of the Mollie extension and are there activate methods displayed when running the API Key Test? If so, are the payment methods showing with the default checkout?

Let me know! 
Thx.

**Comment by Yasp0** [comment]
Yes, the 1.1.4 version.

When running the API test it shows:
Test API-key: Success!Enabled Methods: Ideal, Mistercash, Sofort, Banktransfer, Paypal, Belfius
Live API-key: Empty value

The payment methods are also not showing with the default checkout.

**Comment by Yasp0** [comment]
Hi @Frank-Magmodules ,

Thnx. I send Magmodules a message.

**Comment by Marvin-Magmodules** [comment]
Resolved, frontend output was disabled (core_config_data > modules_disable_output).

**Comment by willemstuursma** [comment]
@Marvin-Magmodules can you add this to an FAQ? It seems rather trivial.

**Comment by Marvin-Magmodules** [comment]
@willemstuursma, yes just added: https://github.com/mollie/magento2/wiki/Troubleshooting

**8. Check if module output has been disabled** 

Located in the core_config_data tabel under path "advanced/modules_disable_ouput/Mollie_Payment". This ability to disable module output has been removed from the Magento Admin since Magento 2.2. If you disabled module output from the Magento Admin in a previous release, you manually need to remove this line from the core_config_table. If you have installed the module on Magento 2.2 or higher, please check the <Magento_install_dir>/app/etc/config.php file, see [Magento DevDocs](http://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html)
