### ISSUE TITLE
Flash message after canceling order is not being shown in checkout.

### ISSUE THREAD

**Issue by Aquive** [mollie/magento2#461]
**Describe the bug**
When a payment it canceled. The flash message (Payment canceled, please try again.) does not get displayed in the checkout. It stays in the session until a non checkout page is loaded, and then it is displayed. E.g. when retrying to do a payment in the same flow, it will display the error on the success page when the payment succeeds. 

**Used versions**
- *Magento Version number(2.4.3-p1)*:
- *Open source*:
- *Mollie version: 2.1.0*:

**To Reproduce**
1. Do checkout steps until you get to the Mollie payment page
2. Cancel the payment (in my case in test mode select cancel option)
3. The browser redirects back to payment selection option in Magento
4. Now go to the homepage. The error message  (Payment canceled, please try again.) will show now.

**Expected behavior**
I am expecting to see the error message (Payment canceled, please try again.) straight away when you are redirected back to the payment selection page in the Magento checkout.

**Actual behavior**
The message is kept in the session until you visit a non-checkout page after canceling the order

**Additional context**
I am testing this on a customized shop. But I switched back to the Luma theme. Problem still exists.

**Comment by Frank-Magmodules** [comment]
HI @Aquive ,

Thank you for opening this issue. 

The “Mollie -> Advanced -> Triggers & Languages -> Redirect user when redirect fails” setting is by default set to “Redirect to cart” because of exactly this reason. 

The default Magento checkout does not include the default message manager used in other parts of Magento. 
For this reason, we included this in the description of the setting: 

> Please be cautious: Depending on the used checkout, error messages may not be displayed.

We are closing this issue now but please feel free to reopen the issue if you have any other comments or questions regarding this issue.
