### ISSUE TITLE
Show Klarna Hints

### ISSUE THREAD

**Issue by sprankhub** [mollie/magento2#586]
# Show Klarna Hints
In the payment method selection during the checkout, it would be nice to show the Klarna-specific hints.

**Backend changes**
None.

**Frontend changes**
If I select a Klarna payment method in the checkout, I would like to have the default Klarna text to be shown there.

**Additional context**

![0UnthACmHANc4tFa](https://user-images.githubusercontent.com/930199/202739169-cfb4195c-7318-42ae-a650-b2241432164f.png)

![wf0ziBRmrUG6y7uK](https://user-images.githubusercontent.com/930199/202739203-f44c3e7e-9c23-49a5-bcf3-c684bb165c08.png)

The core Klarna extension shows these texts.

**Comment by fjbender** [comment]
Hey Simon,

Those texts are generated server-side by Klarna (at least I'm pretty sure). Unfortunately, we don't currently relay the endpoints required - and as we currently rely on the Klarna Hosted Payment Page (instead of the embedded checkout widgets) we might not be able to do this in the near future.

I'll be looking into this some more, but to manage expectations, the Klarna widgets are not something that we can easily support unfortunately.

**Comment by fjbender** [comment]
Unfortunately, I'll have to close this for now, as it is more of a platform issue than something in the plugin. I made a note of it in the Pool of Good Ideas™, though, so your issue was not raised in vain.
