### ISSUE TITLE
ApplePay Support in Hyvä Frontend

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2#649]
The ApplePay integration uses RequireJS frontend technology to build the ApplePay button and functionality.
See https://github.com/mollie/magento2/blob/master/view/frontend/templates/applepay/minicart/applepay-button.phtml for details.
The Mollie_Payment compatibility module at Hyvä is still open https://gitlab.hyva.io/hyva-public/module-tracker/-/issues/262 for 7 month now.
You are talking about alternative frontend support in the Readme https://github.com/mollie/magento2/blob/master/README.md#support-for-other-alternative-frontends, but there are no Hyvä Modules available (except the ones when you use Hyvä Checkout)
What is the timeline for Hyvä compatible integrations in the non checkout parts of the shop?

**Comment by Frank-Magmodules** [comment]
HI There @ThomasNegeli ,  
  
Thank you for bringing up this issue. I would like to clarify that we do indeed support Apple Pay in the frontend, although it may not be explicitly mentioned in the documentation. To access the necessary support module, please visit the following link: [https://github.com/mollie/magento2-hyva-compatibility](https://github.com/mollie/magento2-hyva-compatibility)

Within this repository, you will find two modules: one for supporting Hyva Checkout and another for general Hyva functionality. If you do not utilize the Hyva Checkout, you can disable that specific module.

Please let me know if you have any further questions or concerns so we can close this issue.

**Comment by ThomasNegeli** [comment]
Hi @Frank-Magmodules , thank you for the hint. I will check it out.
Maybe you could clarify the readme text "Hyvä Checkout" to "General Hyvä Compatibility + Hyvä Checkout"

**Comment by Frank-Magmodules** [comment]
I have recently made the necessary updates, @ThomasNegeli. I will now close this ticket under the assumption that everything is clear. However, if there are any remaining concerns, please don't hesitate to inform me.

**Comment by ThomasNegeli** [comment]
@Frank-Magmodules 
* Issue 1: https://github.com/search?q=repo%3Amollie%2Fmagento2-hyva-compatibility%20Magewirephp%5CMagewire%5CComponent%5CForm&type=code
* Issue 2: https://github.com/search?q=repo%3Amollie%2Fmagento2-hyva-compatibility+Hyva%5CCheckout%5CModel%5CMagewire%5CPayment%5CAbstractPlaceOrderService&type=code
You are missing dependencies to those packages in your composer.json

**Comment by Frank-Magmodules** [comment]
Hi There @ThomasNegeli ,  
Thank you for bringing this to our attention and for your efforts in helping us improve our project.

We would like to clarify your observation about the absence of specific requirements in the `composer.json` file. It might be causing some confusion. Our decision to exclude dependencies in the `composer.json` is intentional and was based on the structure of our repository, which contains two distinct modules. Each of these modules has its specific dependencies listed separately in their respective `module.xml` files.

This structure was designed to address interdependencies within our project. For instance, the checkout compatibility module relies heavily on the Hyva Checkout. As such, it’s impossible to enable the former without having the latter installed in your environment. This dependency is declared in the `module.xml` file, which Magento 2 reads when enabling the module.

We understand this might cause a bit of confusion when reviewing the `composer.json` file, as one might expect all dependencies to be listed there. However, we believe our current approach is a better fit for our project’s structure and dependencies. We will, however, consider adding more detailed documentation to clearly explain our dependency management approach and clear any confusion.

Please let us know if you have more questions or suggestions, and thank you for your understanding and contribution.

**Comment by ThomasNegeli** [comment]
Hi @Frank-Magmodules ,
you have a hard dependency in your code. Please review the official Adobe documentation on this topic https://developer.adobe.com/commerce/php/architecture/modules/dependencies/#hard-dependencies
