### ISSUE TITLE
[QUESTION] Bank transfer orders pending payment are being cancelled automatically

### ISSUE THREAD

**Issue by dverkade** [mollie/magento2#657]
**Describe the bug**
Bank transfer orders pending payment are being cancelled automatically by the magento sales_clean_orders cronjob

**Used versions**
- Magento 2.4.6

**Expected behavior**
Pending payment orders should be open until the bank transfer payment window configured in Mollie is over. 

**Actual behavior**
Order is being cancelled by the magento cronjob "sales_clean_orders"

**Comment by Frank-Magmodules** [comment]
Hello @dverkade, thank you for your message. Regarding bank transfers, we are aware of an issue where the default Magento pending status can automatically cancel the order before the payment expiry time. To address this, we have introduced an alternative "pending" status specifically for bank transfer orders.

![](https://github.com/mollie/magento2/assets/24823946/bb8b6f69-521d-4ea5-b02d-09ff7496f904)

We recommend using this new status instead of the default "Pending Payment" status. This new status should be visible to customers, notifying them that they still need to complete their payment.

Additionally, if you wish, you can extend the default Pending Payment Order Lifetime in the Sales > Sales > Orders Cron Settings.

Please let me know if this solution is helpful so that we can consider the issue resolved. We will also make sure to improve the clarity of this configuration and document it accordingly.

![](https://github.com/mollie/magento2/assets/24823946/f3476502-bb3f-423d-9a41-c900ee0ddfe2)

**Comment by Frank-Magmodules** [comment]
Hello @dverkade, could you confirm if this adequately addresses your concern? If so, we can proceed to close this matter.

**Comment by Frank-Magmodules** [comment]
Hello, @dverkade! Based on the fact that there hasn't been any further comment, I assume that this ticket can be closed. However, please feel free to reopen it at any time if you require further assistance or have any additional concerns.
