### ISSUE TITLE
After install though ssh gives error  Class 'Mollie\Api\MollieApiClient' not found in /var/www/html/app/code/Mollie/Payment/Model/Api.php on line 12

### ISSUE THREAD

**Issue by ird2bcet4cse** [mollie/magento2#67]
I am getting after enabling the extension 

ubuntu@$:/var/www/html$ sudo php bin/magento setup:di:compile
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 46.0 Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 50.0 Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 50.0 MiBPHP Fatal error:  Class 'Mollie\Api\MollieApiClient' not found in /var/www/html/app/code/Mollie/Payment/Model/Api.php on line 12
ubuntu@ip-172-31-18-247:/var/www/html$

![image](https://user-images.githubusercontent.com/12964707/42366030-c1d5aa6c-811d-11e8-8f6b-97f42f8e9b95.png)

**Comment by Frank-Magmodules** [comment]
Hi @ird2bcet4cse ,

It looks like you are trying to install the module by FTP, this is not possible due to dependencies. 

There are 2 different methods to install the module:

[1. Install the Mollie extension using Composer ](/mollie/magento2/wiki/Installation-using-Composer)
[2. Install the Mollie extension using the Magento® Marketplace ](/mollie/magento2/wiki/Installation-using-Marketplace)

Have a good day!

**Comment by shivanisehdev86** [comment]
@Frank-Magmodules  Thanks It worked when I installed via composer.

It was an issued because of dependencies
