### ISSUE TITLE
Order confirmation not send when checkout with guest

### ISSUE THREAD

**Issue by barist26** [mollie/magento2#684]
**Describe the bug**

When checkout guests order confirmations emails not sending. I saw mollie.log billingEmail field is null.
"billingEmail":null
it is show order confirmation was sent on order page. But it is don't send.

**Used versions**
Magento ver. 2.4.4 Open source
- Mollie v2.30.0
- 
**To Reproduce**
1. Go to Sales > Checkout > Allow Guest Checkout is YES
2. Click on basket and make order like guest.
3. See the logs mollie.log file "billingEmail":null
 

**Expected behavior**
Must be not null billingaddress

**Actual behavior**
it is null billingaddress

**Screenshots**
![Capture d’écran 2023-08-22 101517](https://github.com/mollie/magento2/assets/86116740/3a80cac5-9576-4660-b64e-0269bd851ce5)
![Capture d’écran 2023-08-22 101545](https://github.com/mollie/magento2/assets/86116740/504a4ae3-d1cf-4987-91cc-3bd62c4a529b)

**Comment by Frank-Magmodules** [comment]
Hello @barist26, I don't think this issue is directly connected to the Mollie plugin, but let's work together to identify the root cause. I'm currently missing some key information about the method you're using and whether this issue is specific to the order or payment API. Could you please provide these details or get in touch with us [directly](https://www.magmodules.eu/support-form.html)? Based on the information we have so far, I'm unable to replicate the problem.

**Comment by barist26** [comment]
Hello Mr. Frannk, your support page don't exists. 

Please reach me in here: 
https://onetimesecret.com/secret/rcrw88yq2wrcqsjplxpemnbjfx5l4su
password: frank




Regards

**Comment by barist26** [comment]
Hello, Mr Frank,
May be you're right, problem not come from module mollie. I will still looking details. 

Thanks
Regards
