### ISSUE TITLE
[BUG] No Online Refund button after payment in Credit Memo

### ISSUE THREAD

**Issue by flagbird** [mollie/magento2#779]
**Describe the bug**
When I order a product in the shop and pay with credit card, I can't do an Credit Memo online refund, because the Refund button isn't available. 

Some research showed me that the transaction id isn't available in the Invoice (It's checked in `Magento\Sales\Block\Adminhtml\Order\Creditmemo\Create\Items`), which is why the button won't appear. 
To be able to do further research about this do I have a question: Where and at which step does the invoice get the transaction id in the Mollie module? I want to be 100% sure if this is a bug of an issue with the Magento project itself with the answer to this question.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.38.0

**To Reproduce**
1. Create a regular order in the shop like a customer and use credit card payment
2. Go to the Magento backend and log in
3. Sales ->Orders
4. Open the order you've created for this test
5. Create an invoice with Online capture
6. Click the created invoice and go to Credit Memo

**Expected behavior**
A "Refund" button is next to the "Offline Refund" button

**Actual behavior**
Only the "Offline Refund" button is available (Because the Invoice has no transaction id)

**Comment by flagbird** [comment]
Thank you for your help.

> Where and at which step does the invoice get the transaction id in the Mollie module?

Can you please help me with this question? I'd like to verify if this is an issue with the module or just happens on certain circumstances with the module, so I can give a reproduceable test.

**Comment by Frank-Magmodules** [comment]
The status check with Mollie is triggered at 2 moments in the whole flow: The moment that a customer returns from the (external) payment page, which may be flakey due to closing the browser too early, and by the webhook. Next to that, there is a “`Fetch Status`” button on the order page in the backend, which triggers the same process. See below.

<img width="575" alt="Scherm­afbeelding 2024-05-23 om 13 41 15" src="https://github.com/mollie/magento2/assets/24823946/47b5c987-7ec9-49b4-bbde-85dcfd24e542">

To answer your question: Whenever we create the invoice, an transaction ID should be set. 
This exact moment depends on your setting. For Klarna this can be at different times, eg after creating the shipment, for other methods this is usually when the status check is done as described earlier.

**Comment by flagbird** [comment]
> Whenever we create the invoice, an transaction ID should be set.
> This exact moment depends on your setting. For Klarna this can be at different times, eg after creating the shipment, for other methods this is usually when the status check is done as described earlier.

Thank you. TODO for myself: Check the Mollie settings in their backend.

**Comment by Frank-Magmodules** [comment]
Sure, @flagbird. Just to confirm, is this issue resolved now? :) If so, please feel free to close the issue.

**Comment by Frank-Magmodules** [comment]
Hi @flagbird, since there has been no response, I consider this issue resolved and am closing it.

**Comment by flagbird** [comment]
It is resolved. Custom Code in the project was the reason for why the invoice was missing + some local dev issues with the webhooks that aren't directly related with mollie/magento2.

Thank you for your assistance. :bouquet:

**Comment by Frank-Magmodules** [comment]
Thanks for confirming that @flagbird ! Have a good day!
