### ISSUE TITLE
Expired payment links cause error

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#794]
**Describe the bug**

Expired payment links cause and error due to the payment link redirect url being `null`. Will add more info as I get further into the problem.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.35.1

**To Reproduce**
- Create a order with payment link
- Let the payment link expire
- Click the link to the payment link (from the admin panel, but I assume it's the same in the mail)

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

`Orders:229` -> the checkout url returned is empty due to `$this->_links->checkout` not set.

**Comment by Frank-Magmodules** [comment]
Hi there, @Swahjak!

It’s been a while! Could you please try to reproduce this issue with our [latest release](https://github.com/mollie/magento2/releases/tag/v2.40.0)? Your report is based on an old(er) version, and we’ve made significant improvements to the payment link logic since then. 

Let me know how it goes. Thanks!

**Comment by Swahjak** [comment]
Hey @Frank-Magmodules, my mistake. I was sure I upgraded to the latest version, but somehow ended up on 2.35.x. Did run into another issue though https://github.com/mollie/magento2/issues/795.

**Comment by Frank-Magmodules** [comment]
No worries, @Swahjak. Thanks for confirming that this is fixed. 
I’ll check out your other issue!
