### ISSUE TITLE
Invoice cannot be captured

### ISSUE THREAD

**Issue by KathiD303** [mollie/magento2#809]
**Describe the bug**
Since 13.8 we're experiencing a problem with orders which are set to processing state although a problem is logged when caputuring the invoice. The issue appears with all active Mollie payment methods (Apple Pay, PayPal, credit card, EPS). When trying to fetch the status from Mollie again nothing happens. Plus, the order id cannot be found in Mollie at all. We did not receive any money for the orders yet, but they are processed and dispatched by our ERP due to the processing state.

**Used versions**
- *Magento Version number: 2.4.5-p9
- *Open source/Enterprise/B2b*: Commerce Cloud
- *Mollie version number: v2.40.1

**To Reproduce**
Unfortunately I cannot reproduce the issue on demand. It appears on a daily basis for a small percentage of all orders (55 in total since 13.8).

**Expected behavior**
invoice can be created for the order

**Actual behavior**
invoice isn't created, order lines are set to invoiced nevertheless

**Screenshots**
![image](https://github.com/user-attachments/assets/80ea1a0b-677b-477d-9d6a-7dea671e81e2)

Can you please help me solve this issue? 

Best regards,
Katharina

**Comment by KathiD303** [comment]
Hello,

update on this case: It seems that this is some incompatibility with the Amazon Pay module we're using. Amazon Pay is enabled in the payment methods by the module setting "Amazon Pay in final checkout step" and is shown besides the Mollie payment options. I assume that the customer tries to proceed with a Mollie payment method, then cancels the payment (not sure in which way exactly) and then proceeds with Amazon Pay. The order is already been created with the Mollie payment method although the payment is later captured by Amazon. I guess this is what causes the issue here.

Best regards,
Katharina

**Comment by Frank-Magmodules** [comment]
Hi @KathiD303,

Thank you for opening this issue and for your response today. The invoice should only be created once a payment has been successfully completed with a status of "`paid`" or "`authorized`." Otherwise, it should remain open or be canceled as needed.

I don’t have a clear way to reproduce this issue directly, and it might be challenging to replicate. However, if you need help with debugging or if you gain new insights, please feel free to respond to this ticket or [contact us](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) directly. We’d be happy to investigate this further with you.

**Comment by Frank-Magmodules** [comment]
Hi @KathiD303, hope you’re doing well! 
Did you have a chance to look into my comment? 
I haven’t received any email, but perhaps our comment already addressed your question or issue. 
If you need more information, just let me know—we’re happy to help!
