### ISSUE TITLE
Payment status is not automatically adjusted upon successful payment.

### ISSUE THREAD

**Issue by mtjweb** [mollie/magento2#811]
When a successful payment is made via Mollie, the feedback from Mollie is not processed. The order keeps the status Pending Payment.

When I retrieve the payment status manually, the status is processed correctly.

In the log I see the feedback:
`[2024-09-01 12:25:29] Mollie.INFO: success: {"success":true,"status":"paid","order_id":"408","type":"success"} [] []`
`[2024-09-01 12:25:29] Mollie.INFO: info: Unlocking: mollie.order.408 [] []`
`[2024-09-01 12:25:29] Mollie.INFO: info: Key "mollie.order.408" unlocked [] []`

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3-p3
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: v2.40.1

PHP 7.4.33

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb,

Thank you for raising this issue. This typically happens when the Mollie servers are unable to connect to your webhook. Common causes include firewall restrictions or Cloudflare settings. Please ensure that the `/mollie/checkout/webhook` path is accessible. You can also review the webhook process within the order details on your Mollie dashboard.

Could you please check this?

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb, great to hear! Once you’ve confirmed that this has resolved your issue, feel free to close the ticket!
