### ISSUE TITLE
Admin order mollie payment link resulting in invoice with 0 orderlines

### ISSUE THREAD

**Issue by downforce80** [mollie/magento2#812]
**Describe the bug**
After admin creates and order with mollie payment link the invoice has 0 orderlines.

**Used versions**
- *Magento Version 2.4.4-p9
- *Open source
- *Mollie version number v2.36.0

**To Reproduce**
1. Create order in magento with mollie payment link

**Expected behavior**
Create the invoice with all orderlines

**Actual behavior**
Invoice with 0 orderlines but right amount in total.

**Screenshots**
<img width="603" alt="Screenshot 2024-09-02 at 16 01 22" src="https://github.com/user-attachments/assets/265c8ae2-6d30-4381-99ae-af263a3019b6">

<img width="1768" alt="Screenshot 2024-09-02 at 16 10 28" src="https://github.com/user-attachments/assets/50a70e68-70be-456b-9b56-3a6aea79f803">

**Comment by Frank-Magmodules** [comment]
Hi @downforce80,

Thank you for opening this issue. I’ve attempted to reproduce it using the [latest Mollie](https://github.com/mollie/magento2/releases/tag/v2.40.1) release but was unsuccessful. Since we've made some significant changes to the payment link logic between your current Mollie module version and the latest one, please update the Mollie plugin and try to replicate the issue again. Let me know if you still encounter any problems.

I’ll keep this comment open until I hear back from you.

**Comment by Frank-Magmodules** [comment]
Hi @downforce80,   could you let me know if you were able to reproduce this issue with our latest Mollie release? Since we haven't received any further information, feel free to respond to this ticket or [contact us](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) directly. If the issue no longer exists, please close the ticket, but we’re happy to investigate further with you if needed.

**Comment by downforce80** [comment]
Hi @Frank-Magmodules i'll ask my team to update it soon

**Comment by Frank-Magmodules** [comment]
Hi @downforce80, hope you’re doing well! Have you received any updates from the team by chance regarding his ticket?

**Comment by simonmaass** [comment]
we actually also had this happen - unfortunately i cannot give more context.

**Comment by Frank-Magmodules** [comment]
Hi @simonmaass, is this issue also occurring on versions later than 2.40.1? 
If you have any steps to reproduce it, I’d be happy to take a look!

**Comment by downforce80** [comment]
Hi @Frank-Magmodules thanks for the followup and support, we've updated the module and haven't seen this issue ever since.

**Comment by Frank-Magmodules** [comment]
Thanks @downforce80, and welcome! @simonmaass, feel free to reopen this issue once you have more detailed feedback and/or additional context on the matter.
