### ISSUE TITLE
Performance On Cart Page

### ISSUE THREAD

**Issue by sprankhub** [mollie/magento2#816]
**Describe the bug**
We're working on some TTFB improvements. So while benchmarking the cart page, we found that a `curl_exec` from Mollie takes almost 300 ms:

    curl_exec(https://api.mollie.com/v2/methods?...amount[value]=...

This comes from `\Mollie\Payment\Model\MollieConfigProvider::getConfig`. Could this somehow be improved? Do we really need to get the payment methods there? Could this be postponed to a later point or be done asynchronously?

Please mind that we use Hyvä / Hyvä Checkout, but when checking the code, even in Luma, the checkout config is loaded in the cart, so it should be the same.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p9
- *Open source/Enterprise/B2b*: Open Soure
- *Mollie version number (Check configuration)*: v2.37.0

**To Reproduce**
1. Go to the cart page
2. Analyse how long `\Mollie\Payment\Model\MollieConfigProvider::getConfig` takes to execute.

**Expected behavior**
`\Mollie\Payment\Model\MollieConfigProvider::getConfig` just takes a few milliseconds.

**Actual behavior**
`\Mollie\Payment\Model\MollieConfigProvider::getConfig` takes almost 300 milliseconds.

**Screenshots**

![image](https://github.com/user-attachments/assets/3c1a880a-a1b8-4332-b5a2-b58cdb2a22c1)

**Additional context**
n/a

**Comment by Frank-Magmodules** [comment]
Thanks, as always, for sharing a potential improvement @sprankhub! 
We’ll review the issue and get back to you soon.

**Comment by Frank-Magmodules** [comment]
Hi There @sprankhub ,

You're right, making that call on the shopping cart page doesn’t make much sense, as the output isn’t actually used there. However, I believe this is more of an issue with how Magento is set up rather than a "Mollie" problem. That said, we have a solution planned for the next release, which will prevent the call from being made on the cart page! 

Regarding the comment about the speed of the API call itself: that’s not something I can address directly, but I’ll pass the feedback on to the Mollie team.

I’ll keep the issue open until we’ve released the new version with this improvement.
Thanks again!

**Comment by fjbender** [comment]
I'll see if we can take a look at the endpoint's speed.

In the meantime, other integrations have the possibility to turn off usage of the Methods API. This could also be a solution here, but it would require users to manually configure the available countries and limits. Especially for larger or performance-critical setups this could help, though.

What do y'all think?

**Comment by Frank-Magmodules** [comment]
Great additions, guys! I’ll discuss the best approach with the team, but it looks like we’re all on the same page! 😉
