### ISSUE TITLE
GooglePay only directs to Credit Card form

### ISSUE THREAD

**Issue by aurel5542** [mollie/magento2#827]
Hello,
I dont know if its a bug but I just updated Mollie for Magento2, activated Google Pay at Mollie Backend and on Magento backend. If I now go to checkout (on desktop, unfortunatly I dont have android phone) it just redirects to a Credit card form. If I select Google Pay in another shop a popup with google-url opens and you can login the Google account. Do I need to do something else to activate Google Pay?
Thank you!

**Comment by fjbender** [comment]
Hi, 
We currently only support Google Pay through our Hosted Payment Page, meaning you get redirected to the Credit Card page where we offer you Google Pay if enabled on your device and browser, and regular Card payments otherwise. We are working hard to provide the experience you describe at a later time :)

**Comment by KathiD303** [comment]
Hi @fjbender

we have the same problem. We've enabled Google Pay on our site ridersdeal.com and the mentioned solution works for Chrome on Android but not for Firefox. On Firefox the Google Pay Button is not shown. Plus on a desktop version Google Pay is also not shown - only credit card

Chrome on Android - works
![image](https://github.com/user-attachments/assets/b01f58a3-a7bd-41b4-aa72-04995e71cf09)

Firefox on Android - doesn't work
![image](https://github.com/user-attachments/assets/295267bc-080c-482f-a6bf-988113eaab16)

Chrome Desktop Version (same: Firefox Desktop) - doesn't work
![image](https://github.com/user-attachments/assets/3d6ecf21-93e8-457a-8f6a-0b9a2d42e259)

Safari: Google Pay is shown - if chosen Apple Pay will be shown on the payment page
![image](https://github.com/user-attachments/assets/9ce19f41-c681-47af-b4fd-5b8f20ab6833)

As you can see there are still a few unexpected behaviors in the Google Pay solution which makes it hard for our users to understand the payment process.

Best regards,
Katharina

**Comment by fjbender** [comment]
Hi @KathiD303,

Those are mostly limitations by Google Pay itself, not by Mollie. Only seeing Google Pay in Google Chrome on Android is expected behavior. 

@hreinberger maybe it's worth considering adding a frontend check whether the browser is eligible for Google Pay and hiding the method selector if it isn't?
